#server:
#  port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
#         git:
#           uri: file:///home/tomillo/Desktop/config
         native:
          searchLocations: classpath:config/,classpath:config/bitcoindAdapter,classpath:config/txMemPool,classpath:config/mempoolRecorder